<div class="form-group gcore-form-row" id="form-row-2"><label for="text1" class="control-label gcore-label-left">Your name</label>
<div class="gcore-input gcore-display-table" id="fin-text1"><input name="text1" id="text1" value="" placeholder="" maxlength="" size="" class="form-control A" title="" style="" data-inputmask="" data-load-state="" data-tooltip="" type="text" /></div></div><div class="form-group gcore-form-row" id="form-row-4"><label for="text2" class="control-label gcore-label-left">Teacher's name</label>
<div class="gcore-input gcore-display-table" id="fin-text2"><input name="text2" id="text2" value="" placeholder="" maxlength="" size="" class="form-control A" title="" style="" data-inputmask="" data-load-state="" data-tooltip="" type="text" /></div></div><div class="form-group gcore-form-row" id="form-row-6"><label for="text3" class="control-label gcore-label-left">Subject</label>
<div class="gcore-input gcore-display-table" id="fin-text3"><input name="text3" id="text3" value="" placeholder="" maxlength="" size="" class="form-control A" title="" style="" data-inputmask="" data-load-state="" data-tooltip="" type="text" /></div></div><div class="form-group gcore-form-row" id="form-row-7"><label for="textarea4" class="control-label gcore-label-left">Short story</label>
<div class="gcore-input gcore-display-table" id="fin-textarea4"><textarea name="textarea4" id="textarea4" placeholder="" rows="3" cols="40" class="form-control A" title="" style="" data-wysiwyg="0" data-load-state="" data-tooltip=""></textarea></div></div><div class="form-group gcore-form-row" id="form-row-8"><label for="file5" class="control-label gcore-label-left">Upload a picture</label>
<div class="gcore-input gcore-display-table" id="fin-file5"><input name="file5" id="file5" class="validate[&#039;image&#039;] form-control gcore-height-auto A" title="" style="" data-load-state="" data-tooltip="" type="file" /></div></div><div class="form-group gcore-form-row" id="form-row-10"><label for="text6" class="control-label gcore-label-left">Video URL</label>
<div class="gcore-input gcore-display-table" id="fin-text6"><input name="text6" id="text6" value="" placeholder="" maxlength="" size="" class="validate[&#039;url&#039;] form-control A" title="" style="" data-inputmask="" data-load-state="" data-tooltip="" type="text" /></div></div><div class="form-group gcore-form-row" id="form-row-12"><label for="text8" class="control-label gcore-label-left">User ID</label>
<div class="gcore-input gcore-display-table" id="fin-text8"><input name="text8" id="text8" value="" placeholder="" maxlength="" size="" class="form-control A" title="" style="" data-inputmask="" data-load-state="" data-tooltip="" type="text" /></div></div><div class="form-group gcore-form-row" id="form-row-13"><div class="gcore-input gcore-display-table" id="fin-button7"><input name="button7" id="button7" type="submit" value="Submit" class="form-control A" style="" data-load-state="" /></div></div>

test