<div class="form-group gcore-form-row" id="form-row-2"><label for="text1" class="control-label gcore-label-top">School name</label>
<div class="gcore-input-wide gcore-display-table" id="fin-text1"><input name="text1" id="text1" value="" placeholder="" maxlength="" size="60" class="validate[&#039;required&#039;] form-control A" title="" style="" data-inputmask="" data-load-state="" data-tooltip="" type="text" /><span class="help-block">As how you want it to appear everywhere</span></div></div><div class="form-group gcore-form-row" id="form-row-4"><label for="text2" class="control-label gcore-label-top">Curriculum board</label>
<div class="gcore-input-wide gcore-display-table" id="fin-text2"><input name="text2" id="text2" value="" placeholder="" maxlength="" size="" class="validate[&#039;required&#039;] form-control A" title="" style="" data-inputmask="" data-load-state="" data-tooltip="" type="text" /><span class="help-block">Example: CBSE, ICSE</span></div></div><div class="form-group gcore-form-row" id="form-row-5"><label for="file3" class="control-label gcore-label-top">School logo</label>
<div class="gcore-input-wide gcore-display-table" id="fin-file3"><input name="file3" id="file3" class="validate[&#039;required&#039;,&#039;image&#039;] form-control gcore-height-auto A" title="" style="" data-load-state="" data-tooltip="" type="file" /><span class="help-block">Example: PNG, JPG, BMP, GIF</span></div></div><div class="form-group gcore-form-row" id="form-row-7"><label for="text4" class="control-label gcore-label-top">Address 1</label>
<div class="gcore-input-wide gcore-display-table" id="fin-text4"><input name="text4" id="text4" value="" placeholder="" maxlength="" size="60" class="validate[&#039;required&#039;] form-control A" title="" style="" data-inputmask="" data-load-state="" data-tooltip="" type="text" /></div></div><div class="form-group gcore-form-row" id="form-row-9"><label for="text5" class="control-label gcore-label-top">Address 2</label>
<div class="gcore-input-wide gcore-display-table" id="fin-text5"><input name="text5" id="text5" value="" placeholder="" maxlength="" size="60" class="form-control A" title="" style="" data-inputmask="" data-load-state="" data-tooltip="" type="text" /></div></div><div class="form-group gcore-form-row" id="form-row-11"><label for="text6" class="control-label gcore-label-top">City</label>
<div class="gcore-input-wide gcore-display-table" id="fin-text6"><input name="text6" id="text6" value="" placeholder="" maxlength="" size="" class="validate[&#039;required&#039;] form-control A" title="" style="" data-inputmask="" data-load-state="" data-tooltip="" type="text" /></div></div><div class="form-group gcore-form-row" id="form-row-13"><label for="text7" class="control-label gcore-label-top">State</label>
<div class="gcore-input-wide gcore-display-table" id="fin-text7"><input name="text7" id="text7" value="" placeholder="" maxlength="" size="" class="validate[&#039;required&#039;] form-control A" title="" style="" data-inputmask="" data-load-state="" data-tooltip="" type="text" /></div></div><div class="form-group gcore-form-row" id="form-row-15"><label for="text8" class="control-label gcore-label-top">Country</label>
<div class="gcore-input-wide gcore-display-table" id="fin-text8"><input name="text8" id="text8" value="" placeholder="" maxlength="" size="" class="validate[&#039;required&#039;] form-control A" title="" style="" data-inputmask="" data-load-state="" data-tooltip="" type="text" /></div></div><div class="form-group gcore-form-row" id="form-row-17"><label for="text9" class="control-label gcore-label-top">ZIP postal code</label>
<div class="gcore-input-wide gcore-display-table" id="fin-text9"><input name="text9" id="text9" value="" placeholder="" maxlength="" size="" class="validate[&#039;required&#039;,&#039;number&#039;] form-control A" title="" style="" data-inputmask="" data-load-state="" data-tooltip="" type="text" /></div></div><div class="form-group gcore-form-row" id="form-row-19"><label for="text10" class="control-label gcore-label-top">Phone</label>
<div class="gcore-input-wide gcore-display-table" id="fin-text10"><input name="text10" id="text10" value="" placeholder="" maxlength="" size="" class="validate[&#039;required&#039;,&#039;phone&#039;] form-control A" title="" style="" data-inputmask="" data-load-state="" data-tooltip="" type="text" /></div></div><div class="form-group gcore-form-row" id="form-row-21"><label for="text11" class="control-label gcore-label-top">Email</label>
<div class="gcore-input-wide gcore-display-table" id="fin-text11"><input name="text11" id="text11" value="" placeholder="" maxlength="" size="" class="validate[&#039;required&#039;,&#039;email&#039;] form-control A" title="" style="" data-inputmask="" data-load-state="" data-tooltip="" type="text" /></div></div><div class="form-group gcore-form-row" id="form-row-23"><label for="text12" class="control-label gcore-label-top">Website</label>
<div class="gcore-input-wide gcore-display-table" id="fin-text12"><input name="text12" id="text12" value="" placeholder="" maxlength="" size="" class="validate[&#039;url&#039;] form-control A" title="" style="" data-inputmask="" data-load-state="" data-tooltip="" type="text" /><span class="help-block">Example: http://scienceclub.com</span></div></div><div class="form-group gcore-form-row" id="form-row-24"><label for="file13" class="control-label gcore-label-top">User data</label>
<div class="gcore-input-wide gcore-display-table" id="fin-file13"><input name="file13" id="file13" class="validate[&#039;required&#039;] form-control gcore-height-auto A" title="" style="" data-load-state="" data-tooltip="" type="file" /></div></div><div class="form-group gcore-form-row" id="form-row-26"><div class="gcore-input gcore-display-table" id="fin-fld25"><a href="/scienceclub/files/userdata.csv">Download</a> sample user data.
<ul>
<li>Users may include students, staff and principal.</li>
<li>Name, unique ID, class or grade information (0 if not a student) is mandatory for all users.</li>
</ul></div></div><div class="form-group gcore-form-row" id="form-row-32"><label for="fld27" class="control-label gcore-label-top">Verification code</label>
<div class="gcore-subinput-container-wide" id="fitem29"><div class="gcore-input pull-left gcore-sub-input gcore-display-table" id="fin-fld28"><input placeholder="" maxlength="" size="" class="validate[&#039;required&#039;] form-control A" title="" style="" type="text" name="captcha" id="fld28" /><span class="help-block">Please type the bold characters only</span></div></div>
<div class="gcore-subinput-container-wide" id="fitem31"><div class="gcore-input pull-left gcore-sub-input gcore-display-table" id="fin-fld30">{captcha_img}</div></div></div><div class="form-group gcore-form-row" id="form-row-33"><div class="gcore-input gcore-display-table" id="fin-button15"><input name="button15" id="button15" type="submit" value="Submit" class="form-control A" style="" data-load-state="" /></div></div>